# Generated by Django 5.2.5 on 2025-08-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='name',
            new_name='type',
        ),
    ]
